'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class QUESTIONNAIREEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=QUESTIONNAIREEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property tbl_CustImage() As DbSet(Of tbl_CustImage)
    Public Overridable Property tbl_Questionnaire() As DbSet(Of tbl_Questionnaire)
    Public Overridable Property tbl_QuestionnaireDetails() As DbSet(Of tbl_QuestionnaireDetails)

End Class
