'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_CustImage
    Public Property CustImageID As Integer
    Public Property CustImage As Byte()

End Class
Partial Public Class tbl_Questionnaire
    Public Property PK As Integer
    Public Property QuestionnaireID As Nullable(Of Integer)
    Public Property Topic As String
    Public Property CustomerID As String
    Public Property EmpID As String
    Public Property SalAreaID As String
    Public Property BranchID As String
    Public Property CustImageID As Nullable(Of Integer)
    Public Property CreateDate As Nullable(Of Date)
    Public Property CreateBy As String
    Public Property UpdateDate As Nullable(Of Date)
    Public Property UpdateBy As String

End Class
Partial Public Class tbl_QuestionnaireDetails
    Public Property QuestionnaireDetailsID As Integer
    Public Property QuestionnaireID As Nullable(Of Integer)
    Public Property Seq As Nullable(Of Integer)
    Public Property Question As String
    Public Property SelectFlag As Nullable(Of Boolean)
    Public Property Score As Nullable(Of Decimal)
    Public Property Remark As String
    Public Property CreateDate As Nullable(Of Date)
    Public Property CreateBy As String
    Public Property UpdateDate As Nullable(Of Date)
    Public Property UpdateBy As String

End Class
