//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tbl_CustImage
{
    public int CustImageID { get; set; }
    public string CustImagePath { get; set; }
    public string CustomerID { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
}

public partial class tbl_CustMaster
{
    public int PK { get; set; }
    public string BranchID { get; set; }
    public string Province { get; set; }
    public string SalAreaID { get; set; }
    public string SalAreaName { get; set; }
    public string VAN_ID { get; set; }
    public string CustomerID { get; set; }
    public string CustName { get; set; }
    public string Telephone { get; set; }
}

public partial class tbl_Customer
{
    public int PK { get; set; }
    public string CustomerID { get; set; }
    public string AssessorName { get; set; }
    public string CustomerType { get; set; }
    public string Latitude { get; set; }
    public string Longitude { get; set; }
    public string Remark { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
}

public partial class tbl_CustQA
{
    public long PK { get; set; }
    public string CustomerID { get; set; }
    public Nullable<int> QuestionnaireID { get; set; }
    public Nullable<int> QuestionnaireDetailsID { get; set; }
    public Nullable<bool> SelectFlag { get; set; }
    public string Text { get; set; }
    public Nullable<decimal> Score { get; set; }
    public string Remark { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
}

public partial class tbl_Questionnaire
{
    public int PK { get; set; }
    public Nullable<int> QuestionnaireID { get; set; }
    public string Topic { get; set; }
    public string Pattern { get; set; }
    public string QAType { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
}

public partial class tbl_QuestionnaireDetails
{
    public int QuestionnaireDetailsID { get; set; }
    public Nullable<int> QuestionnaireID { get; set; }
    public Nullable<int> Seq { get; set; }
    public string Question { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
}

public partial class tbl_User
{
    public int PK { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public string BranchID { get; set; }
    public string FullName { get; set; }
    public string PhoneNo { get; set; }
}

public partial class proc_qa_branch_get_Result
{
    public string BranchID { get; set; }
    public string BranchName { get; set; }
}

public partial class proc_qa_branch_search_Result
{
    public string CustomerID { get; set; }
    public string CustName { get; set; }
}

public partial class proc_qa_customer_get_all_Result
{
    public string CustomerID { get; set; }
    public string CustName { get; set; }
}

public partial class proc_qa_customer_get_Result
{
    public string CustomerID { get; set; }
    public string CustName { get; set; }
    public string ORDERCust { get; set; }
}

public partial class proc_qa_customer_get_ws_Result
{
    public string CustomerID { get; set; }
    public string CustName { get; set; }
}

public partial class proc_qa_get_qa_list_dt_Result
{
    public long PK { get; set; }
    public Nullable<int> QuestionnaireID { get; set; }
    public Nullable<int> QuestionnaireDetailsID { get; set; }
    public string รหัสลูกค้า { get; set; }
    public string ชื่อร้าน { get; set; }
    public string คำถาม { get; set; }
    public string คำตอบ { get; set; }
    public bool เลือก { get; set; }
    public string รายละเอียดคำตอบ { get; set; }
    public string รูปแบบคำถาม { get; set; }
    public string กลุ่มคำถาม { get; set; }
    public Nullable<System.DateTime> วันที่แก้ไข { get; set; }
}

public partial class proc_qa_get_qa_list_Result
{
    public int PK { get; set; }
    public Nullable<long> ลำดับ { get; set; }
    public string รหัสร้าน { get; set; }
    public string ชื่อร้าน { get; set; }
    public string ผู้ประเมิณ { get; set; }
    public string ประเภทร้านค้า { get; set; }
    public string ละติจูด { get; set; }
    public string ลองจิจูด { get; set; }
    public string หมายเหตุ { get; set; }
    public Nullable<System.DateTime> วันที่แก้ไข { get; set; }
}

public partial class proc_qa_get_questionnaire_Result
{
    public Nullable<long> ลำดับ { get; set; }
    public Nullable<int> เลขที่คำถาม { get; set; }
    public string คำถาม { get; set; }
    public int เลขที่คำตอบ { get; set; }
    public Nullable<int> ลำดับคำตอบ { get; set; }
    public string คำตอบ { get; set; }
    public string รูปแบบคำตอบ { get; set; }
    public string กลุ่มคำถาม { get; set; }
    public Nullable<System.DateTime> วันที่สร้าง { get; set; }
    public Nullable<System.DateTime> วันที่แก้ไข { get; set; }
}

public partial class proc_qa_province_get_all_Result
{
    public string BranchID { get; set; }
    public string BranchName { get; set; }
}

public partial class proc_qa_salearea_get_Result
{
    public string SalAreaID { get; set; }
    public string SalAreaName { get; set; }
}

public partial class proc_qa_user_get_Result
{
    public int PK { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public string BranchID { get; set; }
    public string FullName { get; set; }
    public string PhoneNo { get; set; }
}

public partial class proc_qa_van_get_Result
{
    public string van_id { get; set; }
    public string VanName { get; set; }
}
