//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class QUESTIONNAIRE_ALLCEntities : DbContext
{
    public QUESTIONNAIRE_ALLCEntities()
        : base("name=QUESTIONNAIRE_ALLCEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<tbl_CustImage> tbl_CustImage { get; set; }
    public virtual DbSet<tbl_CustMaster> tbl_CustMaster { get; set; }
    public virtual DbSet<tbl_Customer> tbl_Customer { get; set; }
    public virtual DbSet<tbl_CustQA> tbl_CustQA { get; set; }
    public virtual DbSet<tbl_Questionnaire> tbl_Questionnaire { get; set; }
    public virtual DbSet<tbl_QuestionnaireDetails> tbl_QuestionnaireDetails { get; set; }
    public virtual DbSet<tbl_User> tbl_User { get; set; }

    public virtual ObjectResult<proc_qa_branch_get_Result> proc_qa_branch_get(string branchID)
    {
        var branchIDParameter = branchID != null ?
            new ObjectParameter("BranchID", branchID) :
            new ObjectParameter("BranchID", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_qa_branch_get_Result>("proc_qa_branch_get", branchIDParameter);
    }

    public virtual ObjectResult<proc_qa_branch_search_Result> proc_qa_branch_search(string searchText)
    {
        var searchTextParameter = searchText != null ?
            new ObjectParameter("SearchText", searchText) :
            new ObjectParameter("SearchText", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_qa_branch_search_Result>("proc_qa_branch_search", searchTextParameter);
    }

    public virtual ObjectResult<proc_qa_customer_get_Result> proc_qa_customer_get(string branchID, string van_id, string salAreaID)
    {
        var branchIDParameter = branchID != null ?
            new ObjectParameter("BranchID", branchID) :
            new ObjectParameter("BranchID", typeof(string));

        var van_idParameter = van_id != null ?
            new ObjectParameter("van_id", van_id) :
            new ObjectParameter("van_id", typeof(string));

        var salAreaIDParameter = salAreaID != null ?
            new ObjectParameter("SalAreaID", salAreaID) :
            new ObjectParameter("SalAreaID", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_qa_customer_get_Result>("proc_qa_customer_get", branchIDParameter, van_idParameter, salAreaIDParameter);
    }

    public virtual ObjectResult<proc_qa_customer_get_all_Result> proc_qa_customer_get_all(string customerID)
    {
        var customerIDParameter = customerID != null ?
            new ObjectParameter("CustomerID", customerID) :
            new ObjectParameter("CustomerID", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_qa_customer_get_all_Result>("proc_qa_customer_get_all", customerIDParameter);
    }

    public virtual ObjectResult<proc_qa_customer_get_ws_Result> proc_qa_customer_get_ws()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_qa_customer_get_ws_Result>("proc_qa_customer_get_ws");
    }

    public virtual ObjectResult<proc_qa_get_qa_list_Result> proc_qa_get_qa_list(string branchID)
    {
        var branchIDParameter = branchID != null ?
            new ObjectParameter("BranchID", branchID) :
            new ObjectParameter("BranchID", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_qa_get_qa_list_Result>("proc_qa_get_qa_list", branchIDParameter);
    }

    public virtual ObjectResult<proc_qa_get_qa_list_dt_Result> proc_qa_get_qa_list_dt(string customerID)
    {
        var customerIDParameter = customerID != null ?
            new ObjectParameter("CustomerID", customerID) :
            new ObjectParameter("CustomerID", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_qa_get_qa_list_dt_Result>("proc_qa_get_qa_list_dt", customerIDParameter);
    }

    public virtual ObjectResult<proc_qa_get_questionnaire_Result> proc_qa_get_questionnaire(string qAType)
    {
        var qATypeParameter = qAType != null ?
            new ObjectParameter("QAType", qAType) :
            new ObjectParameter("QAType", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_qa_get_questionnaire_Result>("proc_qa_get_questionnaire", qATypeParameter);
    }

    public virtual ObjectResult<proc_qa_province_get_all_Result> proc_qa_province_get_all()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_qa_province_get_all_Result>("proc_qa_province_get_all");
    }

    public virtual ObjectResult<proc_qa_salearea_get_Result> proc_qa_salearea_get(string branchID, string van_id)
    {
        var branchIDParameter = branchID != null ?
            new ObjectParameter("BranchID", branchID) :
            new ObjectParameter("BranchID", typeof(string));

        var van_idParameter = van_id != null ?
            new ObjectParameter("van_id", van_id) :
            new ObjectParameter("van_id", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_qa_salearea_get_Result>("proc_qa_salearea_get", branchIDParameter, van_idParameter);
    }

    public virtual ObjectResult<proc_qa_user_get_Result> proc_qa_user_get(string userName, string password)
    {
        var userNameParameter = userName != null ?
            new ObjectParameter("UserName", userName) :
            new ObjectParameter("UserName", typeof(string));

        var passwordParameter = password != null ?
            new ObjectParameter("Password", password) :
            new ObjectParameter("Password", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_qa_user_get_Result>("proc_qa_user_get", userNameParameter, passwordParameter);
    }

    public virtual ObjectResult<proc_qa_van_get_Result> proc_qa_van_get(string branchID)
    {
        var branchIDParameter = branchID != null ?
            new ObjectParameter("BranchID", branchID) :
            new ObjectParameter("BranchID", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_qa_van_get_Result>("proc_qa_van_get", branchIDParameter);
    }
}
