//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAreaToDistrict
    {
        public decimal AutoNo { get; set; }
        public string AreaID { get; set; }
        public string DistrictID { get; set; }
    }
}
