//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerAM2
    {
        public string CustomerID { get; set; }
        public string CustName { get; set; }
        public string Address { get; set; }
        public string DistrictID { get; set; }
        public string AreaID { get; set; }
        public string ProvinceID { get; set; }
        public string Lattitude { get; set; }
        public string Longtitude { get; set; }
        public string ZoneID { get; set; }
        public string SalAreaName { get; set; }
        public string SlpCode { get; set; }
        public string SlpName { get; set; }
        public string CustImg { get; set; }
    
        public virtual tblProvince tblProvince { get; set; }
    }
}
