//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProvince
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProvince()
        {
            this.tblCustomerAM2 = new HashSet<tblCustomerAM2>();
            this.tblCustomerWS = new HashSet<tblCustomerW>();
            this.tblSalAreaToProvinces = new HashSet<tblSalAreaToProvince>();
            this.tblBranchToProvinces = new HashSet<tblBranchToProvince>();
        }
    
        public string ProvinceID { get; set; }
        public string ProvinceName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerAM2> tblCustomerAM2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerW> tblCustomerWS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalAreaToProvince> tblSalAreaToProvinces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBranchToProvince> tblBranchToProvinces { get; set; }
    }
}
