//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class QUESTIONNAIRE_TESTEntities2 : DbContext
{
    public QUESTIONNAIRE_TESTEntities2()
        : base("name=QUESTIONNAIRE_TESTEntities2")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<tbl_CustImage> tbl_CustImage { get; set; }
    public virtual DbSet<tbl_Customer> tbl_Customer { get; set; }
    public virtual DbSet<tbl_CustQA> tbl_CustQA { get; set; }
    public virtual DbSet<tbl_Questionnaire> tbl_Questionnaire { get; set; }
    public virtual DbSet<tbl_QuestionnaireDetails> tbl_QuestionnaireDetails { get; set; }
    public virtual DbSet<tbl_CustMaster> tbl_CustMaster { get; set; }
}
