//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tbl_CustImage
{
    public int CustImageID { get; set; }
    public string CustImagePath { get; set; }
    public string CustomerID { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
}

public partial class tbl_CustMaster
{
    public int PK { get; set; }
    public string BranchID { get; set; }
    public string Province { get; set; }
    public string SalAreaID { get; set; }
    public string SalAreaName { get; set; }
    public string VAN_ID { get; set; }
    public string CustomerID { get; set; }
    public string CustName { get; set; }
}

public partial class tbl_Customer
{
    public string CustomerID { get; set; }
    public string AssessorName { get; set; }
    public string CustomerType { get; set; }
    public string Latitude { get; set; }
    public string Longitude { get; set; }
    public string Remark { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
}

public partial class tbl_CustQA
{
    public long PK { get; set; }
    public string CustomerID { get; set; }
    public Nullable<int> QuestionnaireID { get; set; }
    public Nullable<int> QuestionnaireDetailsID { get; set; }
    public Nullable<bool> SelectFlag { get; set; }
    public string Text { get; set; }
    public Nullable<decimal> Score { get; set; }
    public string Remark { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
}

public partial class tbl_Questionnaire
{
    public int PK { get; set; }
    public Nullable<int> QuestionnaireID { get; set; }
    public string Topic { get; set; }
    public string Pattern { get; set; }
    public string QAType { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
}

public partial class tbl_QuestionnaireDetails
{
    public int QuestionnaireDetailsID { get; set; }
    public Nullable<int> QuestionnaireID { get; set; }
    public Nullable<int> Seq { get; set; }
    public string Question { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
}
